theme: 
title: Alison Gregory
name: 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Alison Gregory
description: Social Scientist, Community Engagement Specialist, Science Communicator, and Earth Science Advocate
